language: rust
rust: stable

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu

    - env: TARGET=thumbv7m-none-eabi
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=rustfmt
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

before_install: set -e

install:
  - bash ci/install.sh

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo

before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - master
    - staging
    - trying

notifications:
  email:
    on_success: never
